spring.application.name=demo-service

##SPRING DATASOURCE (DATA SOURCE AUTO CONFIGURATION E DATA SOURCE PROPERTIES##
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db
spring.datasource.username=root
spring.datasource.password=root

##SHOW AND FORMAT SQL QUERIES##
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##DDL MODE (CREATE, CREATE_DROP, UPDATE, VALIDATE, NONE)##
#'UPDATE' CREATE OR UPDATE TABLES ON THE BASIS OF THE @ENTITY CLASSES.
spring.jpa.hibernate.ddl-auto=update
